In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import date

df=pd.read_csv("D:\\NSE\\latest\\NFL1.csv")
df

C:\Users\Ashwani-Suyanka\AppData\Local\Temp\ipykernel_9472\2540321744.py:6: DtypeWarning: Columns (52) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("D:\\NSE\\latest\\NFL1.csv")

,Unnamed: 0,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,2010-09-20,2010092000,7,2,1.0,12:19,13,2539.0,42.0,...,-1.872815,0.329797,0.670203,0.313216,0.686784,0.329797,-0.016581,0.047997,-0.064579,2010
49996,49996,2010-09-20,2010092000,7,2,2.0,12:14,13,2534.0,5.0,...,2.179653,0.313216,0.686784,0.359369,0.640631,0.313216,0.046154,-0.029777,0.075930,2010
49997,49997,2010-09-20,2010092000,7,2,1.0,11:25,12,2485.0,49.0,...,0.039600,0.359369,0.640631,0.343103,0.656897,0.359369,-0.016266,-0.019756,0.003490,2010
49998,49998,2010-09-20,2010092000,7,2,2.0,10:42,11,2442.0,43.0,...,0.517356,0.343103,0.656897,0.329942,0.670058,0.343103,-0.013162,-0.033470,0.020308,2010
49999,49999,2010-09-20,2010092000,7,2,3.0,09:59,10,2399.0,43.0,...,4.475560,0.329942,0.670058,0.448566,0.551434,0.329942,0.118625,-0.034346,0.152970,2010

In [6]:
blank=pd.DataFrame(df[df.columns[df.isna().any()]])
blank.isna().sum()

obj=blank[blank.columns[blank.dtypes==object]]
print(obj.columns)
#obj['SideofField'].isnull().sum()
inte=blank[blank.columns[blank.dtypes==float]]
inte['PlayTimeDiff'].describe()

Index(['time', 'SideofField', 'posteam', 'DefensiveTeam', 'ExPointResult',
       'TwoPointConv', 'PuntResult', 'Passer', 'Passer_ID', 'PassOutcome',
       'PassLength', 'PassLocation', 'Interceptor', 'Rusher', 'Rusher_ID',
       'RunLocation', 'RunGap', 'Receiver', 'Receiver_ID', 'ReturnResult',
       'Returner', 'BlockingPlayer', 'Tackler1', 'Tackler2', 'FieldGoalResult',
       'RecFumbTeam', 'RecFumbPlayer', 'ChalReplayResult', 'PenalizedTeam',
       'PenaltyType', 'PenalizedPlayer', 'Timeout_Team'],
      dtype='object')

count    49932.000000
mean        20.851278
std         16.920352
min          0.000000
25%          5.000000
50%         17.000000
75%         38.000000
max        234.000000
Name: PlayTimeDiff, dtype: float64